### ISSUE TITLE
Add name when subscribing

### ISSUE THREAD

**Issue by fxmeister** [igord/sendy-api#7]
As of today, there only exists an option to subscribe emails to lists. It would be a great improvement to add the name field as an optional field as well, like Sendy supports via the web portal.

**Comment by donisback** [comment]
This is already available as part of subscribe API. You can add custom fields too. To add custom fields, you should first add in the list and then add in the calls. I have used it and it works.
Sample example below: 

```
var params = {
    email: 'user@example.com',
    name: 'user',
    list_id: 'your_list_id'
}
```
